language: c++
sudo: false
addons:
  apt:
    packages:
    - cmake
    - g++-7
    - gcc-7
    sources:
    - ubuntu-toolchain-r-test

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc
  gcc /usr/bin/gcc-7 90; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++
  g++ /usr/bin/g++-7 90; fi

script:
- cmake .
- cmake --build .
- ./bctest

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    osx_image: xcode9

    
